name: ci

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.arch }}
    name: Build & Unit Test
    strategy:
      matrix:
        dotnet-version: [ '9.0.x' ]
        arch: ['ubuntu-latest']

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install WASM Workload
        run: dotnet workload install wasm-tools
      - name: Install Dependencies
        run: dotnet restore Overflow.sln
      - name: Build
        run: dotnet build --configuration Debug --no-restore Overflow.sln
      - name: Test
        run: dotnet test --no-restore --verbosity normal Overflow.sln

  build-Docker:

    runs-on: ${{ matrix.arch }}
    name: Build Containers
    strategy:
      matrix:
        arch: ['ubuntu-latest']
    needs: [build] # for ignoring bad builds
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/'))

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Web Container
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            sarsoo/overflow:latest
            sarsoo/overflow:${{ github.ref_name }}
          file: Dockerfile

  # deploy:

  #   runs-on: ubuntu-latest
  #   name: Deploy
  #   needs: [build-Docker] # for ignoring bad builds
  #   if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/'))
  #   environment: 
  #     name: prod
  #     url: https://overflow.sarsoo.xyz
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Tailscale
  #       uses: tailscale/github-action@v2
  #       with:
  #         oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
  #         oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
  #         tags: tag:ci
  #         version: 1.68.1

  #     - name: Deploy
  #       run: ssh -o StrictHostKeyChecking=no ${{ secrets.TS_SSH }} -t "cd overflow/ && docker compose up -d --pull always"