name: ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dotnet-version: [ '8.0.x' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install WASM Workload
        run: dotnet workload install wasm-tools
      - name: Install Dependencies
        run: dotnet restore Overflow.sln
      - name: Build
        run: dotnet build --configuration Debug --no-restore Overflow.sln
      - name: Test
        run: dotnet test --no-restore --verbosity normal Overflow.sln

  build-Docker:

    runs-on: ubuntu-latest
    needs: [build] # for ignoring bad builds
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/'))

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Web Container
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            sarsoo/overflow:latest
            sarsoo/overflow:${{ github.ref_name }}
          file: Dockerfile
